eureka: 
  client: 
    serviceUrl: 
      defaultZone: http://localhost:8761/eureka/      
server: 
  port: 8888
spring: 
  application: 
    name: config-server
  cloud: 
    config:
#      enabled: false
#      bootstrap: true
      label: master
      server: 
        git: 
          uri: https://github.com/tanxinWM/config/
          searchPaths: baojun
